### ISSUE TITLE
تقسيم الصفحة الرئيسية إلى نصفين وإضافة بطاقات للنشاطات أسفل الخريطة

### ISSUE THREAD

**Issue by mslaraba** [GeekAbdelouahed/TouggourtiAndroid#23]

**Comment by GeekAbdelouahed** [comment]
أظن لا حاجة لتقسيم الشاشة لنصفين بالإمكان إضافة سلايد ثاني  ونبقى الخارطة تحتل كامل الشاشة :grey_question:

**Comment by mslaraba** [comment]
من الأفضل التقسيم لأن جميع المعلومات تكون في النصف الثاني وليس في الخريطة

**Comment by mslaraba** [comment]
في الأسفل نضع قائمة للنشاطات أو الأماكن القريبة فهي دائما ظاهرة

القائمة من نوع Listview أو CardView

![image](https://cloud.githubusercontent.com/assets/6674347/18678884/6e1feed0-7f55-11e6-88e7-b5f2cad179b4.png)

**Comment by GeekAbdelouahed** [comment]
نعم مازال راح نعدلها

**Comment by mslaraba** [comment]
المهم في الأعلى خريطة وفي الأسفل قائمة
لايهم نوع سلايد أو أي شيء آخر الهم التقسيم

**Comment by mslaraba** [comment]
كي تكمل قولي بااش ندمج

**Comment by GeekAbdelouahed** [comment]
نورمالمو خلاص 🙌

**Comment by mslaraba** [comment]
ديما كي تكمل أغلق 
issue
باش نعرف
👍
