### ISSUE TITLE
إعادة تسمية النشاطات إلى Business

### ISSUE THREAD

**Issue by mslaraba** [GeekAbdelouahed/TouggourtiAndroid#26]
Touggourti.tk Activity/Activities  
خلط مع 
Android.Activity
ولهذا يجب تسميتها
Business

**Comment by GeekAbdelouahed** [comment]
كيف واش تقصد :question:

**Comment by mslaraba** [comment]
كاينة Activity nta3 android class
Activity النشاط

يسما تتخلط

**Comment by mslaraba** [comment]
👍

**Comment by mslaraba** [comment]
http://touggourti.tk/api/business

**Comment by GeekAbdelouahed** [comment]
:+1:
