### ISSUE TITLE
إظهار النشاطات القريبة والمسافة مع خيار تجميع النشاطات واظهار العدد

### ISSUE THREAD

**Issue by mslaraba** [GeekAbdelouahed/TouggourtiAndroid#8]
تجميع النشاطات يعني مثلا هناك 3 مخابز قريبه. 5 محلات مواد غذاية + 6 مساجد + طبيب واحد

**Comment by GeekAbdelouahed** [comment]
جلب الأنشطة القريبة على مدى 1 كلم

**Comment by mslaraba** [comment]
سنجعل خيار تحديد المدى فيما بعد

**Comment by GeekAbdelouahed** [comment]
Ok

**Comment by mslaraba** [comment]
أغلقو إذا كملت منو، التجميع مبعد نديرولو راي
